### ISSUE TITLE
Is it Possible to Create a Module Federation Example Using a Vite+CRA Combination?

### ISSUE THREAD

**Issue by liaokaime** [kevinuehara/microfrontends-module-federation#2]
You used "vite+vite" and "cra+cra" to create the module federation example, is it possible to work with a combination like vite+cra?

**Comment by kevinuehara** [comment]
@liaokaime yeah it's possible! this example just for example purposes, I decided two apps using CRA (webpack). And another using VIte (Rollup). But the communication between MF's it is independent of the the bundle. So you can use Vite app consuming the CRA.
